title: Northeastern University PEACH Lab
author:
  name: Northeastern University PEACH Lab
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  PEACH Lab is a research lab at the Northeastern University

url: "" # the base hostname & protocol for your site

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

theme: minima