project:
  - title: "Rescriber: Smaller-LLM-Powered User-Led Data Minimization for LLM-Based Chatbots"
    image: "rescriber.jpg"
    venue: CHI '25
  - title: "Secret Use of Large Language Models"
    image: "secret_use.jpg"
    venue: CSCW '25
  - title: "“It's a Fair Game”, or Is It? Examining How Users Navigate Disclosure Risks and Benefits When Using LLM-Based Conversational Agents"
    image: "fairgame.jpg"
    venue: CHI '24